version: '3.9'
services:
  rest-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: detector:latest
    container_name: objectdetector
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
    - 8000:8000
